// AUTO-GENERATED by `npm run rag:build` from src/data/content.ts.
// Do not edit by hand — changes here are overwritten on the next build.

export interface CorpusChunk {
  id: string;
  sourceType: "project" | "experience" | "education" | "skill" | "achievement" | "profile";
  source: string;
  text: string;
  /** Only set on achievement chunks — the API surfaces this to Claude so it
   * can link out without ever inventing a URL. */
  linkedinUrl?: string;
}

export const corpus: CorpusChunk[] = [
  {
    "id": "project-supplysightai-agentic-supply-chain-intelligence",
    "sourceType": "project",
    "source": "SupplySightAI – Agentic Supply Chain Intelligence",
    "text": "Built an agentic AI platform that autonomously analyzes supply chain data, detects risks, explains root causes, forecasts disruptions, and recommends prioritized actions. Tech stack: Python, Pandas, Scikit-learn, Streamlit, Multi-Agent AI."
  },
  {
    "id": "project-parcelpal-route-optimization",
    "sourceType": "project",
    "source": "ParcelPal – Route Optimization",
    "text": "Built a delivery route optimizer with Dijkstra’s Algorithm, improving efficiency and reducing operational costs. Tech stack: JavaScript, React, Node.js, Express, MongoDB, REST APIs."
  },
  {
    "id": "project-ai-enabled-customer-segmentation-churn-prediction-system",
    "sourceType": "project",
    "source": "AI-Enabled Customer Segmentation & Churn Prediction System",
    "text": "Developed predictive models using EDA and behavioral analytics on 100K+ customer records to identify churn risk and enable next-best-action recommendations, improving targeted retention by 12%. Tech stack: Python, Pandas, NumPy, scikit-learn, Predictive Modeling, EDA, Classification, Clustering."
  },
  {
    "id": "project-ai-causal-intelligence-system",
    "sourceType": "project",
    "source": "AI Causal Intelligence System",
    "text": "Built an uplift-based targeting system using causal inference on 100K+ user A/B simulation data to identify high-impact segments and optimize budget allocation, simulating $684K+ incremental revenue. Tech stack: Python, scikit-learn, Causal Inference, A/B Testing, Predictive Modeling, Data Analytics."
  },
  {
    "id": "project-commodity-intelligence-platform",
    "sourceType": "project",
    "source": "Commodity Intelligence Platform",
    "text": "An automated pipeline that extracts raw commodity/market data, processes it through a Microsoft Fabric medallion architecture (bronze → silver → gold), and surfaces it in Direct Lake mode Power BI dashboards for near-real-time decision-making. Automated pipeline that extracts raw commodity/market data, processes it through a Microsoft Fabric medallion architecture (bronze → silver → gold), and surfaces it in Direct Lake mode Power BI dashboards for near-real-time decision-making. Pipeline: Raw Extraction -> Bronze — Raw Ingest -> Silver — Cleansed -> Gold — Curated -> Direct Lake Dashboards. Tech stack: Microsoft Fabric, Power BI (Direct Lake), Medallion Architecture (Bronze/Silver/Gold)."
  },
  {
    "id": "project-commodity-intelligence-platform-stage-extract",
    "sourceType": "project",
    "source": "Commodity Intelligence Platform — Raw Extraction",
    "text": "Raw commodity and market data is pulled from source feeds into the pipeline, unchanged and untransformed — the entry point for everything downstream."
  },
  {
    "id": "project-commodity-intelligence-platform-stage-bronze",
    "sourceType": "project",
    "source": "Commodity Intelligence Platform — Bronze — Raw Ingest",
    "text": "Extracted data lands in the `bronze` layer exactly as received — a raw, append-only landing zone that preserves the original records for lineage and reprocessing."
  },
  {
    "id": "project-commodity-intelligence-platform-stage-silver",
    "sourceType": "project",
    "source": "Commodity Intelligence Platform — Silver — Cleansed",
    "text": "Bronze records are cleaned, validated, and conformed into a consistent schema in the `silver` layer, removing duplicates and standardizing formats."
  },
  {
    "id": "project-commodity-intelligence-platform-stage-gold",
    "sourceType": "project",
    "source": "Commodity Intelligence Platform — Gold — Curated",
    "text": "Silver data is aggregated into business-ready tables in the `gold` layer — the curated, query-optimized layer that reporting tools read from."
  },
  {
    "id": "project-commodity-intelligence-platform-stage-direct-lake",
    "sourceType": "project",
    "source": "Commodity Intelligence Platform — Direct Lake Dashboards",
    "text": "Power BI queries the `gold` layer directly in `Direct Lake` mode — no import or scheduled refresh — so dashboards reflect near-real-time data for decision-making."
  },
  {
    "id": "project-sap-bw-data-integration",
    "sourceType": "project",
    "source": "SAP BW data integration",
    "text": "Integrates SAP BW as a source system into the same Fabric-based pipeline, handling extraction and transformation into the medallion layers feeding downstream reporting. Pipeline: SAP BW Source -> Bronze — Raw Ingest -> Silver — Transformed -> Gold — Curated -> Downstream Reporting. Tech stack: SAP BW, Microsoft Fabric, Medallion Architecture (Bronze/Silver/Gold)."
  },
  {
    "id": "project-sap-bw-data-integration-stage-sap-bw",
    "sourceType": "project",
    "source": "SAP BW data integration — SAP BW Source",
    "text": "`SAP BW` acts as the upstream enterprise source system, supplying the data this pipeline extracts and feeds into the same Fabric-based medallion architecture used across the platform."
  },
  {
    "id": "project-sap-bw-data-integration-stage-bronze",
    "sourceType": "project",
    "source": "SAP BW data integration — Bronze — Raw Ingest",
    "text": "Data extracted from SAP BW lands in the `bronze` layer as raw, unmodified records — the same shared landing zone used by the platform's other source feeds."
  },
  {
    "id": "project-sap-bw-data-integration-stage-silver",
    "sourceType": "project",
    "source": "SAP BW data integration — Silver — Transformed",
    "text": "Raw SAP BW extracts are transformed and conformed into a consistent schema in the `silver` layer, aligning them with the rest of the medallion pipeline."
  },
  {
    "id": "project-sap-bw-data-integration-stage-gold",
    "sourceType": "project",
    "source": "SAP BW data integration — Gold — Curated",
    "text": "Transformed data is curated into business-ready tables in the `gold` layer, ready to feed downstream consumers."
  },
  {
    "id": "project-sap-bw-data-integration-stage-reporting",
    "sourceType": "project",
    "source": "SAP BW data integration — Downstream Reporting",
    "text": "Gold-layer data feeds downstream reporting — the same shared pipeline used by the platform's other dashboards."
  },
  {
    "id": "experience-emerson-graduate-software-engineer-trainee-0",
    "sourceType": "experience",
    "source": "Graduate Software Engineer Trainee at Emerson",
    "text": "Engineered ETL data migration pipelines across enterprise platforms using C# and .NET, reducing manual errors by 60% and improving interoperability"
  },
  {
    "id": "experience-emerson-graduate-software-engineer-trainee-1",
    "sourceType": "experience",
    "source": "Graduate Software Engineer Trainee at Emerson",
    "text": "Developed protocol-aware MODBUS and HART data conversion workflows, maintaining 90%+ data integrity"
  },
  {
    "id": "experience-emerson-graduate-software-engineer-trainee-2",
    "sourceType": "experience",
    "source": "Graduate Software Engineer Trainee at Emerson",
    "text": "Built an LLM-powered internal analytics assistant using Python and prompt engineering, reducing enterprise knowledge retrieval time by 45%"
  },
  {
    "id": "experience-emerson-graduate-software-engineer-trainee-3",
    "sourceType": "experience",
    "source": "Graduate Software Engineer Trainee at Emerson",
    "text": "Automated end-to-end data ingestion, model execution, and deployment using REST APIs and Azure DevOps CI/CD pipelines"
  },
  {
    "id": "experience-emerson-graduate-software-engineer-trainee-4",
    "sourceType": "experience",
    "source": "Graduate Software Engineer Trainee at Emerson",
    "text": "Implemented 15+ data validation rules through system log analysis to improve data quality in production ML pipelines"
  },
  {
    "id": "experience-emerson-graduate-software-engineer-trainee-5",
    "sourceType": "experience",
    "source": "Graduate Software Engineer Trainee at Emerson",
    "text": "Collaborated with cross-functional stakeholders to define KPIs and execute 150+ feature-level test scenarios aligned with business requirements"
  },
  {
    "id": "experience-wizphys-ai-deep-learning-intern-0",
    "sourceType": "experience",
    "source": "Deep Learning Intern at Wizphys AI",
    "text": "Built and shipped real-time exercise detection features for a physiotherapy mobile app using PoseNet keypoint extraction and PyTorch-based classification models"
  },
  {
    "id": "experience-wizphys-ai-deep-learning-intern-1",
    "sourceType": "experience",
    "source": "Deep Learning Intern at Wizphys AI",
    "text": "Engineered skeletal keypoint pipelines and optimized models via hyperparameter tuning and cross-validation, improving prediction accuracy by 15%"
  },
  {
    "id": "experience-wizphys-ai-deep-learning-intern-2",
    "sourceType": "experience",
    "source": "Deep Learning Intern at Wizphys AI",
    "text": "Deployed ML-driven features to production users, increasing session completion and engagement by 18% through iterative performance improvements"
  },
  {
    "id": "education-university-of-texas-at-dallas-ms-in-management-of-information-systems",
    "sourceType": "education",
    "source": "MS in Management of Information Systems, University of Texas at Dallas",
    "text": "MS in Management of Information Systems at University of Texas at Dallas (2025 – 2027), GPA - 3.75/4.0."
  },
  {
    "id": "education-vit-pune-india-bachelor-of-technology",
    "sourceType": "education",
    "source": "Bachelor of Technology, VIT Pune, India",
    "text": "Bachelor of Technology at VIT Pune, India (2020 – 2024), CGPA - 8.77/10.0."
  },
  {
    "id": "skill-programming-development",
    "sourceType": "skill",
    "source": "Programming & Development",
    "text": "Programming & Development: Python, SQL, C#, JavaScript, TypeScript; REST APIs, FastAPI; .NET, MVC Architecture; Git, Azure DevOps CI/CD; Docker."
  },
  {
    "id": "skill-ai-machine-learning",
    "sourceType": "skill",
    "source": "AI & Machine Learning",
    "text": "AI & Machine Learning: Machine Learning, NLP; LLMs (GPT, Claude-style models); Prompt Engineering, Agentic Workflows; GenAI POC Development; AI API Integration, Workflow Automation."
  },
  {
    "id": "skill-frameworks-tools",
    "sourceType": "skill",
    "source": "Frameworks & Tools",
    "text": "Frameworks & Tools: PyTorch, TensorFlow; scikit-learn, OpenCV; LangChain."
  },
  {
    "id": "skill-data-analytics",
    "sourceType": "skill",
    "source": "Data & Analytics",
    "text": "Data & Analytics: EDA, Predictive Modeling; A/B Testing, Behavioral Analysis; Power BI, Tableau; KPI Tracking, Product Analytics."
  },
  {
    "id": "skill-product-skills",
    "sourceType": "skill",
    "source": "Product Skills",
    "text": "Product Skills: Product Strategy; Requirements Gathering; User Stories; Feature Prioritization; Experimentation."
  },
  {
    "id": "skill-applied-ai-enterprise-integration",
    "sourceType": "skill",
    "source": "Applied AI & Enterprise Integration",
    "text": "Applied AI & Enterprise Integration: Azure AI Search indexers (building and tuning search indexes for retrieval); Copilot Studio integrations (building conversational agents on top of enterprise data); LLM failure benchmarking (systematic evaluation of where and why LLM outputs fail)."
  },
  {
    "id": "profile-summary",
    "sourceType": "profile",
    "source": "Yash Mali — profile summary",
    "text": "Yash Mali, AI Engineer / Data Scientist / AI Product Manager. Transforming data and software into intelligent, AI-driven product solutions I’m an AI engineer passionate about building intelligent systems that transform enterprise data into actionable insights and decision-support tools. My work focuses on integrating machine learning models, LLM-powered assistants, and scalable data pipelines into enterprise platforms to automate knowledge access, improve reporting workflows, and enable data-driven decision-making. I’ve developed ETL pipelines across legacy systems, built AI-driven internal analytics assistants to streamline information retrieval, and implemented predictive models to support experimentation and business optimization. I’m particularly interested in applying machine learning, generative AI, and behavioral analytics to solve real-world problems in areas such as experimentation, forecasting, product performance, and operational efficiency. Through my academic and professional experience, I’ve worked on customer segmentation, churn prediction, and uplift-based targeting systems using large-scale behavioral datasets. I enjoy working at the intersection of data science, engineering, and product teams to translate complex business challenges into scalable, AI-enabled solutions that drive measurable impact."
  },
  {
    "id": "profile-contact",
    "sourceType": "profile",
    "source": "Yash Mali — contact",
    "text": "Contact Yash Mali at yashmali597@gmail.com, LinkedIn: https://www.linkedin.com/in/yash-v-mali/, GitHub: https://github.com/YashMali597."
  }
];
