// AUTO-GENERATED by `npm run knowledge:build` from lib/agent/tools.ts.
// DO NOT EDIT BY HAND — your changes will be overwritten.
//
// Input shapes are read from each tool's real Zod schema; output shapes are
// observed by invoking the tool at build time. The /system page renders this,
// so the documented registry cannot drift from the actual tool definitions.

export interface ToolField {
  name: string;
  type: string;
  optional: boolean;
  description?: string;
}

export interface ToolDoc {
  name: string;
  description: string;
  /** False for tools the graph calls directly but never exposes to the model. */
  boundToModel: boolean;
  input: ToolField[];
  output: ToolField[];
  outputError?: string;
}

export const toolRegistry: ToolDoc[] = [
  {
    "name": "getProject",
    "description": "Get the full documented detail of ONE specific project by its exact slug: title, one-line summary, skills, tech stack, timeframe, links, and the full Problem / Architecture / Key decisions / Challenges / Impact sections. Use this when the user asks about a particular project in depth (how it worked, why a decision was made, what the outcome was). You must already know the slug — call listProjects first if you don't.",
    "boundToModel": true,
    "input": [
      {
        "name": "slug",
        "type": "string",
        "optional": false,
        "description": "Exact project slug, e.g. \"commodity-intelligence-platform\". Not the display title."
      }
    ],
    "output": [
      {
        "name": "found",
        "type": "boolean",
        "optional": false
      },
      {
        "name": "project",
        "type": "{ slug, title, oneLiner, skills, stack, timeframe, links, sections, sourceFile, missingSections }",
        "optional": false
      }
    ]
  },
  {
    "name": "listProjects",
    "description": "List every documented project as a short summary (slug, title, one-line description, skills). Use this to help someone browse what Yash has built, to answer 'what projects has he worked on', or to find the right slug before calling getProject. Returns summaries only — it does NOT include the detailed narrative sections.",
    "boundToModel": true,
    "input": [],
    "output": [
      {
        "name": "count",
        "type": "number",
        "optional": false
      },
      {
        "name": "projects",
        "type": "{ slug, title, oneLiner, skills }[]",
        "optional": false
      }
    ]
  },
  {
    "name": "getExperience",
    "description": "Get Yash's professional work history: every role with employer, dates, accomplishment bullets, and tech stack. Use this for questions about jobs, employers, work history, years of experience, or what he did at a particular company. This covers EMPLOYMENT only — for personal or portfolio projects use listProjects/getProject instead.",
    "boundToModel": true,
    "input": [],
    "output": [
      {
        "name": "count",
        "type": "number",
        "optional": false
      },
      {
        "name": "roles",
        "type": "{ slug, title, employer, dates, location, links, highlights, stack, sourceFile }[]",
        "optional": false
      },
      {
        "name": "note",
        "type": "undefined",
        "optional": true
      }
    ]
  },
  {
    "name": "getAchievements",
    "description": "Get Yash's documented achievements — awards, recognitions, publications, talks, and certifications — each with its date and LinkedIn post URL. Use this ONLY for questions about awards, honors, recognition, publications, talks, or certifications. Do NOT use it for project outcomes or job accomplishments; those come from getProject and getExperience. May legitimately return zero entries.",
    "boundToModel": true,
    "input": [],
    "output": [
      {
        "name": "count",
        "type": "number",
        "optional": false
      },
      {
        "name": "achievements",
        "type": "{ slug, title, date, type, linkedinUrl, description, sourceFile }[]",
        "optional": false
      }
    ]
  },
  {
    "name": "getSkillsOverview",
    "description": "Get every skill Yash has documented, mapped to the projects that used it. Use this for questions about what technologies or capabilities he has, whether he has used a specific technology, or how much experience he has with something. Returns evidence (which projects used each skill), NOT ratings — there are no proficiency scores in this system.",
    "boundToModel": true,
    "input": [],
    "output": [
      {
        "name": "totalSkills",
        "type": "number",
        "optional": false
      },
      {
        "name": "skills",
        "type": "{ skill, projects, projectCount }[]",
        "optional": false
      },
      {
        "name": "note",
        "type": "string",
        "optional": false
      }
    ]
  },
  {
    "name": "searchKnowledge",
    "description": "Semantic search across the entire knowledge base. Use only as a fallback when no more specific tool fits — prefer getProject, listProjects, getExperience, getAchievements, or getSkillsOverview whenever the question matches one of those.",
    "boundToModel": false,
    "input": [
      {
        "name": "query",
        "type": "string",
        "optional": false,
        "description": "Natural-language search query."
      },
      {
        "name": "sourceType",
        "type": "\"project\" | \"experience\" | \"education\" | \"achievement\" | \"profile\" | \"skills\" | \"system\"",
        "optional": true,
        "description": "Restrict the search to one section of the knowledge base."
      }
    ],
    "output": [
      {
        "name": "count",
        "type": "number",
        "optional": false
      },
      {
        "name": "results",
        "type": "{ score, heading, documentTitle, sourceType, sourceSlug, sourceFile, text }[]",
        "optional": false
      }
    ]
  }
];

export interface ModelConfig {
  router: string;
  generation: string;
  fallback: string;
  embedding: string;
  embeddingDimensions: number;
}

/**
 * The model ids actually configured in lib/agent/models.ts.
 *
 * Generated rather than typed into the diagram by hand: the /system page
 * displays these, and both original ids (llama-3.1-8b-instant,
 * gemini-2.0-flash) were retired by their providers during development. A
 * hand-written diagram had already drifted to naming dead models.
 */
export const modelConfig: ModelConfig = {
  "router": "openai/gpt-oss-20b",
  "generation": "openai/gpt-oss-120b",
  "fallback": "gemini-3.6-flash",
  "embedding": "Xenova/all-MiniLM-L6-v2",
  "embeddingDimensions": 384
};
